### ISSUE TITLE
cat tmp_align_fasta.aln" (Error Number: "256" - Child error message: "")

### ISSUE THREAD

**Issue by Beuret** [JCVenterInstitute/VIGOR4#20]
Performing an analysis using VIGOR3 and the bunya db, i got following error:

Problems executing the following command: "cat tmp_align_fasta.aln" (Error Number: "256" - Child error message: "")

How can i troubleshoot?

Many thanks and cheers
Christian

**Comment by jchriste-jcvi** [comment]
Hi Christian,

I suspect that the temporary alignment file wasn't produced by clustalw. In prod3/VIGOR.pm I would take a look at the output from clustalw by adding a line like:

print  `cat $vigorspace/tmp_align_fasta.log`, "\n";

just after it runs clustalw with 

&runCmd($vigorspace, $cmd);

I hope that helps,

James

**Comment by jchriste-jcvi** [comment]
This is a Vigor3 issue, so closing.
