### ISSUE TITLE
 java.base/java.lang.Double cannot be cast to java.base/java.lang.Integer

### ISSUE THREAD

**Issue by Aworwui** [JCVenterInstitute/VIGOR4#21]
I'm runing vigor with sarscov2 ref database name and get this error message below:
Command line arguments: -i fastp_report/assembly_out/023/023_contigs.fasta -o ./annot/023_annot -d sarscov2 -c 90
Current working directory: rwui/covid
alignment_module                                  exonerate (defaults)
alignment_score_factor                            1.0 (/shared/software/VIGOR_DB/Reference_DBs/sarscov2_db.ini)
circular_genome                                   false (commandline)
exonerate_path                                    xonerate-2.2.0/bin/exonerate (/shared/software/vigor-4.1.2/config/vigor.ini)
frameshift_sensitivity                            1 (commandline)
leakystop_notFound_score                          80.0 (defaults)
leakystop_score_factor                            1.0 (/shared/software/VIGOR_DB/Reference_DBs/sarscov2_db.ini)
locus_tag                                         vigor_ (commandline)
mature_pep_mincoverage                            50.0 (defaults)
mature_pep_minidentity                            25.0 (defaults)
mature_pep_minsimilarity                          40.0 (defaults)
max_aa_overlap                                    10 (defaults)
max_align_merge_aa_gap                            10 (defaults)
max_gene_overlap                                  50 (/shared/software/VIGOR_DB/Reference_DBs/sarscov2_db.ini)
max_intron_size                                   2500 (defaults)
max_nt_overlap                                    30 (defaults)
min_gene_coverage                                 10.0 (commandline)
min_missing_AA_size                               10 (defaults)
min_pseudogene_coverage                           80.0 (defaults)
min_pseudogene_identity                           70.0 (defaults)
min_pseudogene_similarity                         80.0 (defaults)
min_seq_gap_length                                20 (defaults)
output_directory                                 covid/./annot (commandline)
output_formats                                    [ALN, CDS, PEP, GFF3, TBL] (defaults)
output_prefix                                     023_annot (commandline)
reference_database_file                          VIGOR_DB/Reference_DBs/sarscov2_db (commandline)
reference_database_path                           /VIGOR_DB/Reference_DBs (/shared/software/vigor-4.1.2/config/vigor.ini)
splicing_score_factor                             1.0 (/shared/software/VIGOR_DB/Reference_DBs/sarscov2_db.ini)
start_codon_search_window                         50 (defaults)
start_codons                                      [ATG] (defaults)
start_score_factor                                1.0 (/shared/software/VIGOR_DB/Reference_DBs/sarscov2_db.ini)
stop_codon_search_window                          50 (defaults)
stop_score_factor                                 1.0 (/shared/software/VIGOR_DB/Reference_DBs/sarscov2_db.ini)
temporary_directory                               /tmp/vigor-temp (/shared/software/vigor-4.1.2/config/vigor.ini)
verbose                                           false (commandline)
Getting alignments for NODE_1_length_1076_cov_5576.461461
1 alignment(s) found for sequence NODE_1_length_1076_cov_5576.461461
1 candidate model(s) found for sequence NODE_1_length_1076_cov_5576.461461
Exception encountered: exiting 1
java.lang.ClassCastException: java.base/java.lang.Double cannot be cast to java.base/java.lang.Integer
	at org.jcvi.vigor.service.GeneModelGenerationService.filterModelsWithStructuralSpecifications(GeneModelGenerationService.java:225) ~[vigor-4.1.20190809-171720-7fa683e-jar-with-dependencies.jar:?]
	at org.jcvi.vigor.service.GeneModelGenerationService.generateGeneModel(GeneModelGenerationService.java:67) ~[vigor-4.1.20190809-171720-7fa683e-jar-with-dependencies.jar:?]
	at org.jcvi.vigor.Vigor.generateGeneModels(Vigor.java:395) ~[vigor-4.1.20190809-171720-7fa683e-jar-with-dependencies.jar:?]
	at org.jcvi.vigor.Vigor.modelsFromNucleotideRecord(Vigor.java:297) ~[vigor-4.1.20190809-171720-7fa683e-jar-with-dependencies.jar:?]
	at org.jcvi.vigor.Vigor.generateAnnotations(Vigor.java:240) ~[vigor-4.1.20190809-171720-7fa683e-jar-with-dependencies.jar:?]
	at org.jcvi.vigor.Vigor.run(Vigor.java:87) [vigor-4.1.20190809-171720-7fa683e-jar-with-dependencies.jar:?]
	at org.jcvi.vigor.Application.main(Application.java:12) [vigor-4.1.20190809-171720-7fa683e-jar-with-dependencies.jar:?]

please help

**Comment by Aworwui** [comment]
suspect the error is coming from this line 
int min_coverage = config.getOrDefault(ConfigurationParameters.GeneMinimumCoverage, 0);
line 225 in GeneModelGenerationService.java

**Comment by jchriste-jcvi** [comment]
Thanks for the feedback! I'll take a look at it and let you know what I find.

**Comment by jchriste-jcvi** [comment]
I pushed the fix that changes that int to a double in that line. Thanks for the bug report. I'll close this when I add a test.

**Comment by jchriste-jcvi** [comment]
Close fixed bugs.
